name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    push:
      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "magzapp"
          heroku_email: "ziraqyoung@outlook.com"
